class Chapter {
  final int questionno;
  final String question;
  final String answer;

  Chapter(this.questionno, this.question, this.answer);
}

final chapter1 = [
  Chapter(1, "Define Data and Information.",
      "Data:\n• Data is a raw and unorganized fact that is required to be processed to make it meaningful. Data can be numbers, characters, symbols, image, etc.\n\nInformation:\n• Information is a proceed data in a meaningful way according to the given requirement. For e.g: Bijay is 21 years old."),
  Chapter(2, "What is Database?",
      "Database is a collection of related data that are organized in useful manner."),
  Chapter(
      3,
      "What is Database Management System? What are the advantages of it.",
      "A DBMS is a set of programs that manages the database files. It allows accessing the files, updating the records and retrieving data as requested.\n\nAdvantages of DBMS:\n1. Sharing data is possible,\n2.	Reduce data redundancy [Duplication of Data],\n3.	Easy Data backup and recovery,\n4. Data integrity,\n5. Data security,\n6.	Data independence."),
  Chapter(4, "What are the different types of database model?",
      "Hierarchical Database Model:\n• It is one of the oldest type of database model, It is a type of data model in which the data are organized into a tree-like structure.\n\nNetwork Database Model:\n• It is a database model that allows multiple records to be linked to the same owner file. It replaced hierarchical network database model due to some limitations on the model. Suppose, if an employee relates to two departments, then the hierarchical database model cannot able to arrange records in proper place.\n\nRelational Database Model:  \n• In this model, the data is organized into tables which contain multiple rows and columns. These tables are called relations. A row in a table represents a relationship among a set of values. Since a table is a collection of such relationships, it is generally referred to the mathematical term relation, from which the relational database model derives its name.\n\nEntity-Relationship Database Model: \n• In this model is based on perception of a real world that contains a collection of basic objects, called entities and of relationship among these objects and characteristics of an entity. It shows relationship between different entities."),
  Chapter(
      5,
      "What are the advantages & disadvantage of hierarchical database model?",
      "\t• Advantage:\n- Easiest & Secure Model.\n- Searching is easy and fast, if parent is known.\n- Handle one to many relationship.\n- Build complex system from simple components.\n\n• Disadvantage:\n- Outdated Model.\n- Cannot handle many to many relationship.\n- Create data redundancy.\n- If we delete parent node, all child node will deleted."),
  Chapter(
      6,
      "What are the advantages & disadvantage of network database model?",
      "\t• Advantage:\n- Flexible Model.\n- Accept many to many relationship.\n- Fast seaching.\n\n• Disadvantage:\n- Complex Model.\n- Need large program to handle relationship.\n- Less secured model."),
  Chapter(
      7,
      "What are the advantages & disadvantage of relational database model?",
      "\t• Advantage:\n- Flexible Model.\n- Accept many to many relationship.\n- Fast seaching.\n\n• Disadvantage:\n- Complex Model.\n- Need large program to handle relationship.\n- Less secured model."),
  Chapter(
      8,
      "What is data integrity?  Write its importance while designing database.",
      "Data integrity means the validity of data contained in database. It reflects to overall completeness, accuracy and consistency of data.  It can be maintained by reducing errors, using data validation etc.\n\nImportance of data integrity while designing database.\n1. To check the validity of the data stored in database, \n2. To minimize error in input to process of data,\n3. To define the format of data according to the need of the user,\n4. To ensure that field used as primary key is not null."),
  Chapter(9, "What are the types of data integrity?",
      "Entity Integrity:\n• It ensures that the field used as primary key doesn’t have Null values.\n\nDomain integrity: \n• It ensures that the data provided for a field is within the valid range.\n\nReferential Integrity:\n• It ensures that each values of foreign key should have matching value of primary key."),
  Chapter(10, "What is normalization? Write its advantages.",
      "Normalization is the process of breaking down larger table into smaller tables.\n\n Advantages:\n1. It reduces the data redundancy, \n2. It reduces the wastage of storage,\n3. It makes database operation easier,\n4. It simplifies the structure of tables,\n5. It improves the performance of system."),
  Chapter(11, "What is RDBMS?",
      "The database system which stores and displays data in tabular format of rows and columns, like spreadsheet, is known as Relational Database Management System.\n\nExamples of RDBMS are: MS-Access, Oracle, SQL Server SQL etc."),
  Chapter(12, "What is data security? How it can be implemented?",
      "Data security is the method of protecting the data and other resources of computer system against destruction and unauthorized access. It can be maintained in following levels:\n1. Physical Security: Hardware Level\n2. Logical Security: Software Level\n\nImplementation\n1. By creating Backup,\n2. Using password,\n3. Keep system away from disaster,\n4. Use antivirus software."),
  Chapter(13, "Explain 1NF, 2NF & 3NF.",
      "First Normal Form (1NF):\n• A table or a relation is said to be in 1NF, if it is atomic i.e. it shouldn’t contain any repeating group in any row or column of the table. Each of the table contain only one value. To convert the table into repeating values are decomposed into separate row, column or table.\n\nSecond Normal Form(2NF):\n• A table or a relation is said to be in 2NF, if it is in 1NF and each non key attribute is functionally dependent on the entire primary key. Purpose of 2NF is to eliminate partial key dependencies. To convert table in 1NF into 2NF, the non key attributes which are not function dependent on the primary key are decomposed into separate table.\n\nThird Normal Form (3NF):\n• A table or a relation is said to be in 3NF, if it is in 2NF and transitive dependency doesn’t exist. Every non key attribute should not be transitively dependent on the primary key. To convert the table in 2NF into 3NF, the non key attributes which are transitively dependent on the primary key must be decomposed into separate table."),
  Chapter(14, "What is MS Access? Write its components.",
      "MS Access the a powerful RDBMS[Relational Database Management system] developed by Microsoft and can be used to store and manage large data.\n\nComponents:\n1. Table,\n2. Form,\n3. Query,\n4. Reports."),
  Chapter(15, "Who is Database Administrator[DBA]? Write roles of DBA",
      "A Database Administrator (DBA) is a person responsible for making strategic and policy decisions regarding data and the database as well controlling all the operating of database. DBA  provides necessary strategic and technical supports for the implementation.\n\nRoles:\n1. Design the database,\n2. Monitor the database and its performance,\n3. Design and implement the security policies,\n4. Define the backup and recovery process of the database."),
  Chapter(16, "What is Centralized Database? Write its advantages.",
      "In a centralized database system, database is stored and maintained in a single central location. It works on the basis of client server technology.\n\nAdvantages:\n1. Data and database are secured,\n2. Data redundancy is minimized,\n3. Database Maintenance is easy.\n\n"),
  Chapter(17, "What is Distributed Database? Write its advantages.",
      "Distributed database system is system stored data on several computers and databases located at different places. It facilitates easy access of data from any location and need more computer resources.\n\nAdvantages:\n1. Easy access of data from any location,\n2. Failute of computer or database won't affect system,\n3. Data access is easy.\n\n"),
  Chapter(18, "Write Short Notes on:",
      "Domain:\n• A domain describes the set of possible values for a give attribute, and it can be considered as a constraint on the value of the attribute.\n\nTuples:\n• A tuple is a complete row of the table, It is also called as record.\n\nSQL:\n• SQL stands for Structured Query Language. SQL use simple English and mathematical statements for designing and database operations. It is a common language used in most of the databases.\n\nDML:\n• DML(Data Manipulation Language) is a database language used for database operations such as inserting, accessing, updating, deleting data etc.\n\nDDL: \n•DDL stands for Definitional Language. DDL is a database language used for specifying contents and structure of database. For defining the schema for database."),
];

final chapter2 = [
  Chapter(1, "Define Internet. What are the uses of internet?",
      "The internet is the interconnected network of thousand of network and millions of computers linking businesses. education etc.\n\nUses:\n1. Search Information,\n2. E-mail service,\n3. Communication,\n4. Remote Login,\n5. Publishing of online matter."),
  Chapter(2, "What is communication?",
      "Communication is the process of sending, receiving, and processing of information by electronic media."),
  Chapter(3, "Define Networking with advantages and disadvantages.",
      "The process of connected computers sharing resources is called networking.\n\nAdvantages:\n1. Resource sharing,\n2. Centralized control,\n3. Speedy communication,\n4. Backup and recovery.\n\nDisadvantages:\n1. Expensive,\n2. Security Problem,\n3. Complex,\n4. Network Failure."),
  Chapter(4, "Define LAN, MAN, WAN.",
      "Local Area Network[LAN]:\n• Local Area Network is the inter connection of computers in a small area such as in room, floor, or buildings on one site. It is smaller simple and cheaper than other network. Faster for network data transmission connects limited number of computers.\n\nMetropolitan Area Network[MAN]:\n• It covers a city. It is faster than LAN and slower than wan, cable optical fiber are used in it and expensive than LAN. IT is also used in bank or other types of organization.\n\nWide Area Network[WAN]:\n• A wide area network is even a larger form of network than MAN. The WAN expands beyond cities and covers the national and international locations. It is larger network it covers the whole country. Optical fiber, satellite or point-to-point wireless. It is most expensive and also difficult."),
  Chapter(5, "What is Transmission Media? Write its types.",
      "Transmission media is a communication channel that carries the information from the sender to the receiver. Data is transmitted through the electromagnetic signals.\n\nTypes:\n1. Guided Media:\n• Also called wired media.\n• Transmits the data in the form of electrical or optical signal.\n• Transmits data through specific path. \n• Transmission speed is generally faster.\n• Eg: Twisted pair cable, coaxial cable, optical fiber, etc.\n\n2. Unguided Media:\n• Also called wireless media.\n• Transfers the data in the form of electromagnetic signals. \n• Transmits the data through air.\n•  Transmission speed in generally slower. \n• Eg: Radio waves, satellite communication, etc."),
  Chapter(6, "Define peer-to-peer architecture and client-server architecture.",
      "In peer-to-peer architecture, all computer have equal authority to access data and therefore are known as peers."),
  Chapter(7, "Describe OSI/ISO Model of Networking.",
      "OSI[Open Systems Interconnection] is a reference model for how applications communicate over a network. \nIt contain following layers:\n\nApplication Layer: \n• It interacts the software based like browser, messenger, e-mail, software, etc.\n\nPresentation Layer:\n• It transfers the data in binary format and vice versa by ASCII, UNICODE, etc. Also performs encryption and decryption.\n\nSession Layer:\n• This layer used to establish and maintain session. Session is time period which data transfers through server.\n\nTransport Layer:\n•This layer is responsible for flow control mechanism also ensures data are delivered without error. Also correct the error detected.\n\nNetwork Layer: \n• It is concerned with the addressing and routing. Addressing is done by IP address.\n\nDatalink Layer: \n• It provides function and procedures required to transfer data. It also translates the data packets.\n\nPhysical Layer: \n• It consists of physical components that transmit the data from sender to receiver such as transmission media, NIC, modem etc."),
  Chapter(8, "Define Analog and Digital Signal.",
      "Data are represented in any of the two forms: analog and digital form. In basic term, analog is the continuous and digital is the discrete representation of data. These two terms are used in communication.\n\nAll communication signal is the electromagnetic representation of data.\nExample of electromagnetic signal is human voice. When someone speaks the analog form of signal is produced. The digital signal is the voice stored in binary form 0 and 1 and played through speaker."),
  Chapter(9, "Write Short Note On:",
      "Repeater:\n• Repeater is an electronic device that receives a signal and retransmits it.\n\nHub:\n• A hub is a network hardware device for connecting multiple ethernet devices together and making them act as a single network segment.\n\nBridge:\n•  Bridge is a computer networking device that creates a single aggregate network from multiple communication networks or network segments. \n\nSwitch:\n• It is a computer networking device that connects devices on a computer network by using packet switching to receive, process, and forward data to the destination device.\n\nModem:\n• It stands for modulator and demodulator hardware device that converts data into a format suitable for a transmission medium so that it can be transmitted from computer to computer.\n\nRouter:\n• A router is a networking device that forwards data packets between networks."),
];
final chapter3 = [
  Chapter(1, "What is an HTML? List out any three advantages of HTML?",
      "➡️ HTML (HyperText Markup Language) is a markup language which provides the structure of a website so that web browsers know what to show.\n\nThree advantages of HTML are:\n• It is easy to code,\n• HTML-based web sites are static,\n• HTML-based web sites are easy to design and have low development cost."),
  Chapter(2, "What are HTML tags and where are they used?",
      "➡️ HTML tags are the instruction which define that how web browser will format and display the content.\n\nThey are used to create html document."),
  Chapter(3, "What is CSS? Write the advantages of CSS.",
      "➡️ CSS (Cascading Style Sheets) is a style sheet language which is used to describe the look and formatting of a document written in markup language.\n\nThe advantages of CSS are:\n• Device Compatibility,\n• Faster website speed,\n• Ability to re-position."),
  Chapter(4, "Write down the syntax of CSS.",
      "➡️ The syntax of CSS is: Selector {property: value).\nBody {color: yellow; font-size: 13px;}.\n"),
  Chapter(5, "What are the different types of CSS? Explain.",
      "➡️ The different types of CSS are:\nExternal CSS:\n• External CSS is used to make changes on multiple pages.\n\nInternal CSS:\n•	Internal CSS is used to add a unique style for single document.\n\nInline CSS:\n•	Inline CSS is used to insert stylesheet in html document. "),
  Chapter(
      6,
      "Where the inline, embedded and external style sheets are written?",
      "➡️ External style sheet is written in outside from the html document and save with .CSS extension.\nEmbedded stylesheet is written in html document at head section.\nInline stylesheet is written with html code at body section."),
  Chapter(7, "What is javascript? Write the features of javascript.",
      "➡️ JavaScript (js) is a light-weight object-oriented programming language which is used by several websites for scripting the webpages. \n\nThe features of javascript are:\n• Less server interaction,\n• Immediate feedback to the visitors,\n• Increased interactivity,\n• Rich interfaces."),
  Chapter(8, "What is PHP? Write down the basic syntax of PHP.",
      "➡️ PHP (Hypertext Preprocessor) is a server side scripting language that is used to develop static websites or dynamic websites or web applications.\n\n The basic syntax of php is:\n <?php\n PHP code here \n ?>"),
];

final chapter4 = [
  Chapter(1, "What is while loop?",
      "In the while loop test condition is evaluated before the loop is executed."),
  Chapter(2, "What is do-while loop?",
      "In do-while loop the test condition evaluated after the loop is executed."),
  Chapter(3, "What is pointer?",
      "Pointers is a variable that stores/points the address of another variable. It is similar to other variable but it stores address in place of data."),
  Chapter(4, "What is control structure?",
      "Control structure defines the order in which statement of the program are executed. It determines the flow of control in the program. Different control statement used are: Sequence, Condition and Looping. Else statement is conditional statement. It is used to test whether the statement is true or false."),
  Chapter(5, "What is operator?",
      "An operator is a symbol that tells the compiler to perform a certain mathematical or logical manipulation."),
  Chapter(6, "What is function?",
      "A function is a group of statements that together perform a task. Every C program has at least one function, which is main(), and all the most trivial programs can define additional functions."),
  Chapter(7, "What is Array?",
      "Array is the collection of data items which will have the same name. The individual array elements are distinguished from one another by value that is assigned to a subscript or index."),
];

final chapter5 = [
  Chapter(1, "What is OOP?",
      "The object oriented programming is a programming model that uses “object” to design applications and computer programs. It is a collection of cooperative objects, and each object is capable of receiving messages, processing data, and sending message to the other objects."),
  Chapter(2, "Write the features of OOP.",
      "• A Problem are divided into objects,\n• Data hiding is possible,\n• It is easy to add new data,\n• It is not possible ta access data freely,\n• It uses bottom-up programming technique."),
  Chapter(3, "Write advantages and disadvantages of OOP.",
      "Advantages:\n\n• The complexity of the software can be merged easily, \n• New data can be easily coded,\n• We can define the user defined data types.\n\nDisadvantages:\n\n• Use of OOP is waste of time in small project,\n• OOP are much larger than other program,\n• OOP require a lot of work to create."),
  Chapter(4, "What is procedural oriented programming[POP]?",
      "Procedural Programming can be defined as a programming model which is derived from structured programming, based upon the concept of calling procedure."),
  Chapter(5, "How OOP is differs from POP.",
      "• In OOP, importance is given to data than procedure whereas in POP, emphasis is given to procedure.\n• OOP uses bottom-up development process whereas in POP uses top down development process.\n• Class and object is the main stream of OOP whereas function (library or user defined) are the main stream of POP.\n• OOP includes features such as data abstraction, encapsulation, modularity, polymorphism and inheritance but POP doesn’t include these features.\n• In OOP, programs development will be easier due to features like inheritance, polymorphism, and data encapsulation but in POP, program development will be comparatively top difficult."),
  Chapter(6, "Name the tools that are used in program design.",
      "Program design tools are used by system analyst or programmer to develop the logical sequence for the solution of the program or task. It is used before coding a program systematically. These tools are algorithm, flowchart, Pseudo code, decision table, decision tree, data flow diagram context diagram, E-R diagram, CASE tool, UML, use case, prototyping model etc."),
  Chapter(7, "Explain the terms Polymorphism and Inheritance.",
      "Polymorphism:\n• Polymorphism enables the same function to behave differently on different classes. Object oriented languages try to make existing code easily modifiable without actually changing the code. Polymorphism means that the same function may behave differently in different classes.\n\nInheritance:\n• Inheritance is the property that allows the reuse of existing class to build new class. Principle in this sort of division is that each subclass shares common properties with the class from which it is derived. For example, all vehicles in a class may share similar properties of having wheels and a motor."),
  Chapter(8, "What are the uses/application of OOP.",
      "• AI based system,\n• Expert system,\n• DSS (Decision Support System), \n• Real time systems."),
  Chapter(9, "Write the short note on.",
      "Class:\n• A class is a collection of similar objects that have same properties, common behavior and relationships. A class of persons, a class of animals are the example of class.\n\n Object:\n• A object is a self-contained component that contain properties and methods needed to make a certain type of data useful.\n\n Encapsulation:\n• Encapsulation is the process that allows selective hiding data and functions in class. All communication to object done via message."),
];

final chapter6 = [
  Chapter(1, "What is System?",
      "👉A system can be defined as collection of interrelated components, that work tougher to meet a common goal. It is derived from the Latin word “Systema” which means place tougher. It has three basic components i.e. input, process and output."),
  Chapter(2, "List different stages of System Development Life Cycle[SDLC].",
      "The different stages of SDLC are:\n\n1. System Study,\n2. System Analysis,\n3. System Design,\n4. System Development,\n5. System Testing,\n6. System Implementation,\n7. System Maintenance and Review.\n\nFormula: SAD TIM"),
  Chapter(3, "Who is system Analyst?",
      "System analyst is a person who is involved in analyzing, designing, implementing and evaluating computer based information to support the decision making and operation of an organization."),
  Chapter(4, "List the characteristics of good System Analyst.",
      "The characteristics of good System Analyst are:\n\n1. Knowledge of organization,\n2. Technical Knowledge,\n3. Good communication skill,\n4. Problem solving skill,\n5. System analysis and design skills,\n6. Character and ethics."),
  Chapter(5, "What is the importance of Data Flow Diagram?",
      "Data Flow Diagram[DFD] graphically describe a system’s data and how the data interact with the system. The importance of DFD is to provide analysis that helps to the system analyst to determine the activities of the system. It shows, what data are essential to each activity, what data are stored, what data to enter and leave from the system."),
  Chapter(6, "Write short note on Physical System, C.A.S.E and P.I.E.C.E.S.",
      "Physical System:\nPhysical system contains hardware components input, output, memory and processing devices. It requires software to perform task.\n\nC.A.S.E:\nCASE means Computer Aided System/Software Engineering. CASE tool is a resource for achieving high-quality and error-free software. Most case tools include project management, data dictionary and documentation support.\n\nP.I.E.C.E.S:\nIt is framework for understanding and identifying requirements. It is used to classify various problems, opportunities, and directives identified in system.\n\nAcronym:\nP- Performance\nI- Information\nE- Economics\nC- Control\nE- Efficiency\nS- Service"),
  Chapter(
      7,
      "What is Feasibility Study? Write Reason to conduct feasibility study.",
      "Feasibility study is carried by Systems Analysts. The feasibility study or analysis carefully examines technical, economic, operational, scheduling, legal and strategic factors of a system to make sure that the system can be successfully developed.\n\nSome reason to conduct a feasibility study:\n1. It determines whether the system meet the users goal or not.\n2. It determines strength and weakness before developing system.\n3. It suggests new opportunity through investigation process.\n4. It provides quality information for decision making and documentation.\n5. It focuses on the boundary of the system outline."),
  Chapter(8, "What are the different levels of feasibility study?",
      "The different levels of feasibility study are:\n1. Technical Feasibility: It concerns with the availability of the hardware, software and the support equipment’s for the complete development of the system.\n\n2. Economic Feasibility: It determines the cost and benefit of the purposed system and compares with the budget.\n\n3. Operational Feasibility: It concerns with smooth operation of the system. It is all about the problems that may occur during operation of the system after its development.\n\n4. Social Feasibility: It determines whether a purposed system will be acceptable to the people or not.\n\n5. Time Feasibility. It determines the deadline to complete a system and schedule the task accordingly.\n\n6. Legal Feasibility: It concerns with legal issue of the system. If the system is illegal, then the system designing is meaningless. Everything is measured whether it is legal or illegal."),
  Chapter(9, "Write short note on System Testing.",
      "Testing is the process of executing a program with the intent of finding an error. Testing is an integral part. The testing process move from the individual component out to the system as a whole. \nSome types of system testing:\n\n1. White Box Testing:\n White box testing is a method of testing software that is based on knowledge of how the software is intended to function. White box testing is also called as structural testing or glass-box testing.\n\n2. Black Box Testing:\nBlack box testing focuses on how the software functions without reference to how it is designed. The primary concern is whether the program works or not, how it is constructed. Black box testing is also known as functional testing."),
  Chapter(10, "What is data security? How it can be implemented.",
      "Data security is the process of keeping data protected from corruption, modification by unauthorized user, leakage and physical harms. It can be implemented from following levels:\n\n1. Physical Security: It is concerned with protection from physical damage by keeping data in safe place/environment and using proper backup plan.\n\n2. Logical Security: It is concerned with protection from unauthorized access by using proper authentication and users access control mechanism."),
  Chapter(11, "What is expert system?",
      "An expert system is a computer based system that used artificial intelligence(AI) technique to simulate the judgment and behavior of the human or organization that has expert knowledge in particular field. \nExpert System automates the decision-making process in a specific area, such as medical diagnoses or review of credit history for loan approvals.\n\n1. Rectangle: It represents entity in database. An entity can be a person, place or object.\n2. Oval: It represents attributes of an entity. An attribute is a properties or characteristics of the entity.  If teacher is entity then attributes can be t_id, t_phone, t_address etc.\n3. Diamond: It represents the relationship between two entities. \n4. Line: It is used as connector between relationship and entity, entity and attributes."),
  Chapter(
      12,
      "What is ER Diagram?  Write the meaning of graphical symbols used in it.",
      "E-R Diagram is the designing tool used for designing a database. It is used to show entities, relation between entities, attributes of entities along with the primary attribute of a database using graphical symbol."),
  Chapter(13, "What is Information System? List its types.",
      "An information system is a computer based system which is an integrated set of different components for collection, process, storage and transmission of data. Simply, it us a system which processes supplied/collected data and generates information that can be used for decision making at different levels for the betterment of an organization. \nThe types of information system are:\n\n1. Transaction processing system:\nIt processes data resulting from business transactions, updates operational database such as sales and inventory processing and accounting systems.\n\n2. Management information system:\nIt is the integrated modern approach of management, information and computerized system. It provides information to support the operations, management, decision making functions of an organization.\n\n3. Decision support system:\nIt is the information system at the organization's senior level management that combines data and sophisticated analytical models or data analysis tools to support semi-structures and unstructured decision makings.\n\n4. Executive support system:\nIt is also known as executive information system. It operates on the executive level of management. It provides critical information from many sources customized to the information needs of executives."),
  Chapter(14, "Write Short note on Waterfall model.",
      "Waterfall model is  a type of linear-sequential life cycle model. In a waterfall model, each phase must be completed before the next phase can begin and there is no overlapping in the phases.\n\nAdvantages:\n1. Simple and easy to understand and use,\n2. Clearly defined stages,\n3. Well understood milestones,\n4. Easy to arrange tasks.\n\nDisadvantages:\n1. No working software is produced until late during the life cycle,\n2. High amounts of risk and uncertainty,\n3. Not a good model for complex and object-oriented projects,\n4.Poor model for long and ongoing projects."),
  Chapter(15, "Write Short note on prototype model.",
      "Prototype is a working model of software with some limited functionality. It this model, a prototype is developed instead of developing the full working model. This model is useful to systems where requirements are not known in detail during the development.\n\nAdvantages:\n1. Increased user involvement in the product,\n2. Users get a better understanding of the system,\n3. Reduces time and cost as the defects can be detected much earlier,\n4. Missing functionality can be identified easily.\n\nDisadvantages:\n1. Risk of insufficient requirement analysis owing to too much dependency on the prototype,\n2. Users may get confused in the prototypes and actual systems,\n3. Developers may try to reuse the existing prototypes to build the actual system, even when it is not technically feasible,\n4.The effort invested in building prototypes may be too much if it is not monitored properly."),
];
final chapter7 = [
  Chapter(1, "What is Artificial Intelligence?",
      "Artificial intelligence is the simulation of human intelligence processes by machines, especially computer systems."),
  Chapter(2, "Write the Components of AI.",
      "• Philosophy,\n• Mathematics,\n• Economics,\n• Neuroscience,\n• Psychology."),
  Chapter(3, "Write advantages and disadvantages of Cloud Computing.",
      "Advantages:\n\n• Cost efficient, \n• Unlimited Storage,\n• Backup and Recovery.\n\nDisadvantages:\n\n• Technical Issue,\n• Security,\n• prone to attack."),
  Chapter(4, "What is Big Data?",
      "The definition of big data is data that contains greater variety, arriving in increasing volumes and with more velocity. This is also known as the three Vs. Put simply, big data is larger, more complex data sets, especially from new data sources."),
  Chapter(5, "What is Virtual Reality?",
      "• Virtual Reality (VR) is a computer-generated environment with scenes and objects that appear to be real, making the user feel they are immersed in their surroundings. This environment is perceived through a device known as a Virtual Reality headset or helmet.."),
  Chapter(6, "What is E-Commerce and it's types?",
      "E-commerce (electronic commerce) is the buying and selling of goods and services, or the transmitting of funds or data, over an electronic network, primarily the internet. These business transactions occur either as business-to-business (B2B), business-to-consumer (B2C), consumer-to-consumer or consumer-to-business."),
  Chapter(7, "Define E governance.",
      " E-governance is defined as the application of ICT in establishing interaction between the different levels of government, business and the citizenry. E-governance also involves implementing internal government operations meant to simplify and improve both the democratic and business aspects of Governance."),
  Chapter(8, "What are the areas of Big data?",
      "• Academia,\n• Banking,\n• Manufacturing , \n• Transportation."),
  Chapter(9, "Write the short note on.",
      "Mobile computing:\n• Mobile computing is human–computer interaction in which a computer is expected to be transported during normal usage, which allows for the transmission of data, voice, and video.\n\n IoT:\n• The Internet of Things describes physical objects with sensors, processing ability, software, and other technologies that connect and exchange data with other devices and systems over the Internet or other communications networks.\n\n Social Media:\n• Social media are interactive digital channels that facilitate the creation and sharing of information, ideas, interests, and other forms of expression through virtual communities and networks."),
];
final chapter_1 = [
  Chapter(1, "What is computer? Explain the basic operation of computer.",
      "➡️ A Computer is an electronic device, which takes input from user, process them and provide meaningful result.\n\nBasic operations of computer are:\nInput:\n• Input is any Information the computer collects from the outside world.\n• Examples are keyboard, pointing devices, scanners, etc.\n\nProcess:\n• Processing is the manipulation of the raw data on the basis of the instruction.\n• Central Processing Unit is a device in which computer processes data.\n\nStorage:\n• Storage is the place where data is held in an electromagnetic or optical form for access by a computer processor.\n\nOutput:\n• Output is the any information which computer sends to the outside world.\n• Examples are Computer monitors, printers and speakers, etc."),
  Chapter(2, "Explain any five characteristics of a computer.",
      "➡️ The characteristics of a computer are:\nSpeed:\n• A modern computer can execute millions of instructions in one second. It can be measured in terms of Millisecond, Microseconds, Nanoseconds, Picoseconds, etc.\n\nAccuracy:\n• A computer is highly accurate device. Computer error caused due to incorrect input data or unreliable program are often referred to as garbage-in garbage-out (GIGO).\n\nStorage Capability:\n• A computer has high data storage capacity. The storage capacity of computer can be increased by using secondary storage devices such as magnetic disk, optical disk and flesh driver. The storing capacity of computer is measured in terms of-\na.	Kilobyte – 1024 bytes,\nb.	Megabyte – 1024 kilobytes,\nc.	Gigabyte – 1024 Megabytes,\nd.	Terabytes – 1024 Gigabytes,\ne.	Petabyte – 1024 Terabytes.\n\nAutomatic:\n• Computer is automatic machine because one’s task is initiated, a computer can proceed on its own till its completion.\n\nDiligent:\n• The computer is capable of performing task repeatedly at the same level of speed and accuracy."),
  Chapter(3, "Why computer is known as versatile machine? Explain.",
      "➡️ A computer is known as versatile machine because:\n• It can be used for all sorts of applications ranging from complex calculation in scientific research and space research,\n• Computer can perform more than one task at same time."),
  Chapter(4, "Why computer is so popular? Explain in details.",
      "➡️ Computer is so popular because:\n• It is very accurate and fast,\n• It can do very big calculations in small time."),
  Chapter(5, "Explain any five applications area of computers.",
      "➡️ Some of the common applications area of computers are:\n\nEducation:\n• Computers are used in education sector through online classes, online examinations, referring e-books, online tutoring, etc.\n\nEntertainment:\n• Computers can be used to watch movies online, watching videos, play games online, listening to music, etc.\n\nBusiness Application:\n• Computer can be used for business for various purpose like stocks, prices, sales, investment, keeping account information, etc.\n\nScientific Research:\n• Various scientific research like robotics, nuclear research can be done with computer.\n\nMedical Field:\n• Computers can be used in medical field to keep the database of patients and doctors. Computer can be used in ICU and X-ray."),
  Chapter(6, "What is Napier’s Bones? Who invented it?",
      "➡️ Napier’s Bones is a small instrument which is made by 10 rods with multiplication table was engraved. Strips of ivory bones are used in Napier’s Bones. John Napier invented it in 1614."),
  Chapter(7, "Who is known as the father of modern digital computers? ",
      "➡️ Charles Babbage is known as father of modern digital computers. He designed ‘Difference Engine’ and ‘Analytical Engine’, which are used to computing mathematical tables."),
  Chapter(8, "What did Herman Hollerith invent?",
      "➡️ Herman Hollerith invented a mechanical tabulating machine in 1887. This machine is designed to assist in summarizing information stored on punched cards and for rapid data processing."),
  Chapter(
      9,
      "Why is John Von Neumann a remarkable name in the history of computers?",
      "➡️ John Von Neumann is a remarkable name in the history of computers because he contributed a new understanding of how practical fast computers should be organized and built; these ideas, often referred to as the stored-program technique. He undertook a study of computation that demonstrated that a computer could have a simple, fixed structure, yet be able to execute any kind of computation given properly programmed control without the need for hardware modification."),
  Chapter(
      10,
      "What is generation of computer? Explain the technology used in different generation computers.",
      "➡️ The development of computer took place in different distinct stages, which is known as generation of computer. In every new generation speed, storage, size, reliability of circuit in computer is advancement.\n\nTechnology used in different generation computers are:\nFirst Generation (1946-1958):\n• Vacuum tubes are developed.\n•	Speed of operation is measured in milliseconds.\n• Include the use of punched cards to input and store data.\n\nSecond Generation (1959-1964):\n•	Used transistor as main logic element.\n•	Speed of operation is measured in microseconds.\n•	Assembly language is used.\n\nThird Generation (1965-1974):\n• Used integrated circuit (IC) technology.\n•	Speed of operation is measured in nanoseconds.\n•	Monitors and keyboards are used.\n\nFourth Generation (1975-1990):\n• Used Large Scale Integration (LSI) and Very Large-Scale Integration (VLSI) technologies.\n•	Microcomputers are also introduced.\n•	Magnetic disk is used as external storage.\n\nFifth Generation:\n• Used Ultra Large-Scale Integration (ULSI) technology.\n• Using of intelligent programming.\n• Have faster and larger primary and secondary storage."),
  Chapter(11, "Explain the types of computer on the basis of size.",
      "➡️ On the basis of size computer are classified as:\n\nSuper computer:\n• They are extremely powerful computers used for manipulating large amount of data.\n•	They have large memory capacity and can perform complex scientific calculations.\n•	The speed of supercomputers is generally measured in “FLOPS”.\n•	Examples are Blue Gene/L, IBM ASCI White, etc.\n\nMainframe computer:\n• They have huge memory and extremely rapid processing power.\n• They are mainly used in large organizations for various applications.\n•	Examples are VAX 8842, IBM System z9, etc.\n\nMinicomputer:\n• Minicomputers also called as mid-range servers, are more powerful computers than microcomputers in terms of processing power and capabilities.\n• They have multiuser system where many users work on the system simultaneously.\n• They are used in medium sized organization.\n•	Examples are VAX 7500, Interdata 8/32, etc.\n\nMicrocomputer:\n•	They are small digital computer with microprocessor, single semiconductor integrated circuit chip in CPU.\n•	It is designed for using by one person at a time but now it can network together.\n• They include desktop computer, palmtop, pocket computer, laptop, etc."),
  Chapter(12, "What is mobile computing? Write its features.",
      "➡️ Mobile computing is a wireless communication and its applications are generic technology that refers to numerous devices that are supportable to access transmitted data like voice, video, and text anytime and anywhere over the wireless network infrastructure.\n\nThe features of mobile computing are as follows:\n•	Good battery life,\n•	Having fast processor speed,\n•	Durability,\n•	Easy to handle and carry these small devices,\n•	Data can be transferred easily between users."),
  Chapter(13, "Write short notes on:",
      "Abacus:\n• It is developed by Chinese in 3000 B.C.\n•  It is still used by millions of people throughout Asia.\n• It has rectangular wooden frame with rods carrying round beads.\n\nENIAC:\n•	Developed by John Mauchly and John Eckert in 1946.\n•	Known as Electronic Numerical Integrator and Calculator.\n•	This machine could discriminate the sign of number, compare quantities for equality, add, subtract, multiply, divide and extract square roots.\n•	It consists of 18000 vacuum tubes with 160KW electricity and weight 30 tons.\n\nEDVAC:\n•	Designed by John William Mauchly and John Presper Eckert jr.in 1946.\n•	Known as Electronic Discrete Variable Automatic Computer.\n•	It included a stored program, a central processor and a memory for both data and programs.\n•	It consists of approximately 4000 vacuum tubes.\n•	It consumed 56 Kilowatts of electric power."),
  Chapter(
      14,
      "What is computer architecture? Write the main components of computer architecture.",
      "➡️ Computer architecture is a science or a set of rules stating how computer software and hardware are joined together and interact to make a computer work.\n\nThe main components of computer architecture are as follows:\nInput devices:\n•	Input is the data entered into a computer for processing.\n• Input can be in form of text, program, commands and user response.\n•	The devices which collect input for processing is called input devices.\n•	Keyboard, scanners, digital camera, audio, video are input devices.\n•	The main functions of input devices are: accept data, convert data and sends data in binary form to the computer.\n\nCentral Processing Unit:\n•	CPU is the main information processor in computer capable of executing a program.\n•	CPU serve as “brain” of computer.\n•	It processes the raw data and turns it into information.\n•	It is linked with input/output devices and auxiliary storage units.\n\nMemory:\n•	Memory is blank space where different types of data, programs and software are stored.\n•	There are two types of memory:\na)	Primary memory: Computer memory that is directly accessible to the CPU of computer.\nb)	Secondary memory: Memory that supplements the primary memory. It is long-term and non-volatile. ROM is secondary memory. Examples are magnetic tape, magnetic disk, etc.\n\nOutput Device:\n•	They are peripheral devices that receives or displays output from computer.\n•	Output can be in form of words, numbers, graphics, sounds, etc.\n•	The basic functions of output devices are: Accepts results, convert binary coded data and supplies converted results to the outside world."),
  Chapter(
      15,
      "Define the term “volatile” in the context of computer memory. Which memory is known as volatile memory?",
      "➡️ The term “volatile” in the context of computer memory refers to memory that requires power to maintain the stored information; it retains its contents while powered on but when the power is interrupted, the stored data is quickly lost.\n\nPrimary memory is known as volatile memory."),
  Chapter(16, "Write the difference between RAM and ROM.",
      "RAM (Random Access Memory):\n1️⃣	It is volatile.\n2️⃣	It is temporary storage.\n3️⃣	It is expensive.\n4️⃣	Allows reading and writing.\n5️⃣	Very faster and uses more power.\n\nROM(Read Only Memory):\n1️⃣	It is non-volatile.\n2️⃣ It is permanent storage.\n3️⃣	It is cheap.\n4️⃣	Allows reading only.\n5️⃣	Fast and uses less power."),
  Chapter(17, "Write the difference between EPROM and EEPROM.",
      "EPROM:\n1️⃣	Erasable programable Read Only Memory.\n2️⃣	Can be erased and reuse.\n3️⃣	Erasure is achieved by exposing the chip to ultraviolet light.\n\nEEPROM:\n1️⃣	Electronically Erasable programable Read Only Memory.\n2️⃣ Can be erased electronically.\n3️⃣ Erasure is achieved by exposing the chip to electric light."),
  Chapter(18, "What is cache memory? What is its advantage?",
      "➡️ Cache memory is a small, high speed memory system that stores copies of the data from the most frequently used main memory locations. It is placed between main memory and CPU.\n\nThe main advantage of cache memory is that it is faster than main memory and it consume less time to load."),
  Chapter(
      19,
      "What is computer keyboard? What is the use of keyboard in a computer system?",
      "➡️ Computer keyboard is the primary input devices in computer.\n\nIt enables the user to enter data and commands into a computer for processing."),
  Chapter(
      20,
      "What is the difference between a computer mouse and a trackball?",
      "Mouse:\n1️⃣	The mouse has to be moved when used.\n2️⃣	Mouse is commonly used.\n3️⃣	A mouse consists of a metal or plastic housing or caring, a ball at its base and is rolled on a flat horizontal surface.\n\nTrackball:\n1️⃣	Trackball is stationary.\n2️⃣	Trackball is rarely used.\n3️⃣	We can use a trackball by the rolling the ball with your palm and fingers."),
  Chapter(
      21,
      "What is smart card reader? List any two applications of smart card.",
      "➡️ Smart card readers are used with smart cards which are a type of plastic technology card with a built-in chip used for electronic processes including personal identification, access control, authentication and financial transactions. Smart card readers obtain or “read” this type of data.\n\nThe applications of smart card are:\n•	Credit card,\n•	SIM card."),
  Chapter(22, "What is digital projector? Where is it used?",
      "➡️ A digital projector is an electronic device that is capable of connecting to a computer or other device and projecting the video output onto a screen or wall. Digital projectors can be either fixed onto the ceiling, placed on a stand or can even be portable.\n\nDigital projectors are used in situations such as office training or presentation sessions, classroom teaching and home cinemas."),
  Chapter(23, "What is a printer? List its types.",
      "➡️ Printer is an output device that produces text and graphics on a physical medium such as paper. Printed information is called hard copy because the information exists physically and is a permanent form of output.\n\nThere are mainly 2 types of printer:\n\nImpact printer:\n•	Impact printer is a printer that uses a mechanical hammering device to produce each character.\n\nNon-impact printer:\n•	Non-impact printers are those in which the printing is done with thermal, chemical, electrostatic laser beam or inkjet technology for printing."),
  Chapter(24, "Differentiate between impact printer and non-impact printer.",
      "Impact printer:\n1️⃣ Impact printers form images and characters by striking a mechanism such as a print hammer or wheel against an inked ribbon, leaving an image on paper.\n2️⃣	They are low speed printer.\n3️⃣	They use old printing technologies.\n4️⃣ They are less expensive.\n5️⃣	They use continuous paper sheet.\n\nNon-impact printer:\n1️⃣ Non-impact printers form characters and images without direct physical contact between the printing mechanism and the paper.\n2️⃣ They are very fast.\n3️⃣ Printing technologies are new.\n4️⃣	They are expensive.\n5️⃣	They use individual paper sheets."),
  Chapter(25, "What is plotter? Where is it used?",
      "➡️ Plotter is a printer that interprets commands from a computer to make line drawings on paper with one or more automated pens.\n\nPlotter is used to produce vector graphics drawings."),
  Chapter(
      26,
      "What is secondary storage? List the main types of secondary storage devices.",
      "➡️ Secondary storage is a long-term memory used to store programs and data for the future reference. It supplements the limited storage capacity and the volatile characteristics.\n\nList of main types of secondary storage devices are:\n•	Magnetic Tape,\n•	Magnetic Disk,\n•	Optical Disk."),
  Chapter(
      27,
      "What is magnetic tape? Why is it called sequential access media?",
      "➡️ Magnetic tape is a non-volatile storage. It is used for storing large volumes of data that are needed to be sequentially accessed and processed.\n\nMagnetic tape is called sequential access media because data of tape can only be accessed in sequential form."),
  Chapter(
      28,
      "What is magnetic disk? Name two types of magnetic disks commonly used in microcomputers.",
      "➡️ Magnetic disk is a secondary storage device which provides large storage capabilities.\n\nTwo types of magnetic disks commonly used in microcomputers are:\n•	Hard Drive,\n•	Floppy Disk."),
  Chapter(29, "What is an optical disk? How does it work?",
      "➡️ Optical disk is a rotating disk coated with a thin metal or some other material that is highly reflective.\n\nOptical disk works in following ways:\nA very fine laser beam is used for recording/reading of data on the disk. The digital data on the optical disk is recorded in the form of microscopic pits and lands. A pit represents a binary 0 and the land represents a binary 1."),
  Chapter(30, "What is a motherboard? What does it contain?",
      "➡️ Motherboard is the central or primary circuit board making up a complex electronic system.\n\nMotherboard contains the CPU, chipset, PCI bus slots, AGP slots, memory sockets and controller circuits."),
  Chapter(31, "What is microprocessor? Write the function of it.",
      "➡️ Microprocessor is a semiconductor device consisting of electronic login circuits manufactured by using either a large-scale integration (LSI) or very-large-scale integration (VLSI) technique.\n\nFunction of microprocessor are:\n•	Decoding instructions,\n•	Responding to I/O generated control signals,\n•	Providing timing and control signals for all elements of the computer,\n•	Fetching instructions and data from memory."),
  Chapter(32, "Write short notes on:",
      "Joystick:\n•	Joystick is an input device consisting of a stick that pivots on a base and reports its angle or direction to the device it is controlling.\n•	Joysticks are often used to control video games and usually have one or more push-buttons whose state can also be read by the computer.\n\nParallel ports:\n•	Parallel port is a type of interface which is used for connecting peripherals in computer.\n•	Parallel ports send multiple bits of data at once (parallel communication), as opposed to serial communication, in which bits are sent one at a time."),
];
final chapter_2 = [
  Chapter(
      1,
      "What is number system? Write the different types of number system.",
      "➡️ Number system is an organized and systematic way of representing numbers.\n\nNumber system are basically of two types:\n•	Non-Positional number System,\n•	Positional Number System."),
  Chapter(2, "What is binary number system?",
      "➡️ Binary number system is a positional number system having base 2. It uses the symbols 0 and 1."),
  Chapter(3, "What is Octal number system?",
      "➡️ Octal number system is a positional number system having base 8. It uses the digits from 0 to 7."),
  Chapter(4, "What is hexadecimal number system?",
      "➡️ Hexadecimal number system is a positional number system having base 16. It uses the alphanumeric values form o to 9 and A to F."),
  Chapter(
      5,
      "Write the method of decimal number system to binary number conversion.",
      "➡️ The method of decimal number system to binary number conversion is:\n•	Divide the decimal number by 2 successively,\n•	Keep a note of the remainder in one column,\n•	Repeat the process until the quotient is zero,\n•	The answer is obtained by writing the answer in the reverse order."),
  Chapter(6, "What is Boolean algebra?",
      "➡️ Boolean algebra is a form of mathematical algebra that is used in digital logic in electronics."),
  Chapter(7, "What are Logic operations/ Boolean operators?",
      "➡️ Logic operations include any operation that manipulate either true or false value."),
  Chapter(8, "What is truth table?",
      "➡️ The truth table is a table used to represent Boolean expression of a logic gate function. It shows the output states for every possible combination of input states."),
  Chapter(9, "What is logic gate? Write the different types of logic gate.",
      "➡️ A logic gate is a building block of digital circuit.\n\nThe different types of logical gate are:\nBasic Logic Gates:\n•	AND Gate,\n•	OR Gate,\n•	NOT Gate.\n\nUniversal Gates:\n•	NAND Gate,\n•	NOR Gate.\n\nCombinational Gates:\n•	X-OR Gate,\n•	X-NOR Gate."),
  Chapter(10, "Write the difference between AND & NAND gate.",
      "AND Gate:\n1️⃣	AND gate produce 0 output when any of the input or all the input are 0, otherwise output will be 1.\n2️⃣	Algebraic expression is Y = A*B.\n3️⃣	AND gate is only AND gate.\n\nNAND Gate:\n1️⃣	NAND gate produce 0 output when all the input are 1, otherwise output will be 1.\n2️⃣	Algebraic expression is Y=(A*B)’.\n3️⃣	NAND gate is the combination of AND and NOT gate."),
  Chapter(11, "Why NAND and NOR Gates are called Universal Gates?",
      "➡️ The NAND & NOR gates are called universal gates because they perform all the logical operations of basic gates like AND, OR, NOT."),
  Chapter(12, "Explain the different Laws of Boolean algebra?",
      "➡️ Different laws of Boolean algebra are:\n\nIdentity Law:\n• “Output is same as the input when input is sum with 0 and and product with 1.”\ni.e. (i) A*1 = 1  (ii) A+0 = A\n\nComplement Law:\n• “Sum of input and its complement is always 1 and product of input and its complements is always 0.”\n\nCommutative Law:\n• “Changing the sequence of the variables does not have any effect on the output.” \ni.e. (i) (A+B) = (B+A)   (ii)  (A*B)=(B*A)\n\nAssociative Law:\n• “The order in which the logic operations are performed is irrelevant as their effect is the same.”\ni.e. (i) (A+B)+C = A+(B+C)  (ii) (A*B)*C = A*(B*C)\n\nDistributive Law:\n• A*(B+C) = A*B + A*C\n\nInversion Law:\n• “Double inversion of A variable results in the original variable itself.” i.e. A ̿ = A"),
  Chapter(13, "State De Morgan’s Theorem.",
      "➡️ First Theorem: “The complement of a sum equals to the product of the complements.” i.e. (A+B)’=A’*B’\n\nSecond Theorem: “The complement of a product equal to the sum of the complements.” i.e. (A*B)’=A’+B’"),
];
final chapter_3 = [
  Chapter(1, "What is software? Write down the types of software.",
      "➡️ Software is the collection of computer programs that provide instructions telling a computer what to do and how to do it.\n\nThere are 2 types of software:\n•	Application software,\n•	System software."),
  Chapter(
      2,
      "What are the differences between Application and System software?",
      "Application software:\n1️⃣	Application software is built for specific tasks.\n2️⃣	Application software is used by user to perform specific task.\n3️⃣	Application softwares are installed according to user’s requirements.\n4️⃣	It is usually expensive.\n\nSystem software:\n1️⃣	System software maintains the system resources.\n2️⃣	System software is used for operating computer hardware.\n3️⃣	System softwares are installed automatically.\n4️⃣	It is cheaper."),
  Chapter(3, "What are the types of system software? Explain.",
      "➡️ Types of system software are:\nUtility programs/software:\n•	It is a computer software designed to help in the management and tuning of operating systems, computer hardware and application software.\n\nLanguage translators:\n•	It converts the programming instructions written in human convenient form into machine language codes that computers understand and process.\n\nDevice drivers:\n•	Driver is a software, provided by a hardware maker that tells the computer’s operating system how to work with the hardware.\n\nOperating system:\n•	An operating system is a computer program that coordinates all the activities among computer hardware devices."),
  Chapter(4, "What are the roles of Operating system?",
      "➡️ The roles of operating system are:\n•	Manage the computer’s resources,\n•	Establish a user interface,\n•	Execute and provide services for applications software."),
  Chapter(5, "Explain any five functions of operating system?",
      "➡️ Functions of operating system are:\n\nI/O Management:\n•	OS manages I/O devices and makes the I/O process effective.\n\nCommand Interpreter:\n•	Command interpreter reads the commands that user types in at a terminal, interprets them and translate them.\n\nMemory Management:\n• Management of primary memory including keeps tracks of primary memory, allocate the memory when a process requests it and De-allocates the memory.\n\nProcess Management:\n•	OS finds the status of processor and processes, chooses a job, chooses processer in the job, allocates the processor and frees the processor.\n\nSecurity:\n•	OS makes sure that only authorized users get access to the computer and its data."),
  Chapter(6, "Write the different types of OS.",
      "➡️Different types of OS are:\n•	Multiuser OS,\n•	Multiprocessing OS,\n•	Multiprogramming OS,\n•	Multitasking OS,\n•	Multithreading OS,\n•	Batch OS,\n•	Time-sharing OS,\n•	Distributed OS,\n•	Network OS,\n•	Real-time OS."),
  Chapter(
      7,
      "What is the difference between multi-user OS and multiprocessing OS?",
      "Multi-user OS:\n1️⃣	In a multiuser OS, more than one user can use the same system at the same time.\n\nMultiprocessing OS:\n1️⃣	In a multiprocessing OS, the execution of multiple processes at the same time."),
  Chapter(8, "Write the difference between GUI and CUI.",
      "GUI (Graphical User Interface):\n1️⃣	In GUI, user interact with applications by making use of graphics.\n2️⃣	In GUI more than one task run simultaneously.\n3️⃣ GUI is much easier to navigate than CUI.\n\nCUI (Character User Interface)\n1️⃣	In CUI, user interact with applications by making use of commands.\n2️⃣	In CUI only one task can run at the time.\n3️⃣ CUI is not easier to navigate than GUI."),
  Chapter(9, "Distinguish between batch processing and online processing.",
      "Batch processing:\n1️⃣	A lag exists between time when the economic event occurs.\n2️⃣ Fewer hardware, programing and training resource are required.\n\nOnline processing:\n1️⃣ Processing occurs when the economic event takes place.\n2️⃣	More resources and dedicated processing capacity and quality are required."),
  Chapter(10, "Explain windows with its features.",
      "➡️ Windows is the type of operating system with easier Graphical User Interface.\n\nSome features of windows are:\nCortana:\n•	Cortana is able to accept voice commands.\n\nFile Explorer:\n•	File Explorer displays your files and folders on the computer.\n\nInternet browser:\n•	Internet browser is used to search for view pages, online shopping, play games, watch videos, etc.\n\nMicrosoft paint:\n•	It is used to create, view and edit image.\n\nTaskbar:\n•	Taskbar displays currently opened programs.\n\nStart menu:\n•	Start menu displays programs and utilities that are installed on the computer.\n\nTask Manager:\n•	Task manager provides details of the running application."),
  Chapter(
      11,
      "What is a desktop? What are the main elements of Windows desktop?",
      "➡️ A desktop is a personal computer design for regular use at single location.\n\nThe main elements of Windows desktop are:\n•	Icon,\n•	Control Panel,\n•	Scroll Bar,\n•	Main menu,\n•	Minimize, maximize and close button, etc."),
  Chapter(12, "Explain the concept of Open-Source OS.",
      "➡️ Open source is a program in which the source code is available to the general public. They permit users to the use, change and improve the software. Some Open-Source OS are Ubuntu, Linux, etc."),
  Chapter(13, "Write short notes on:",
      "Files and Folders:\n•	File is the common storage unit in a computer, and all programs and data are “written” into a file and “read” from a file.\n•	A folder holds one or more files, and a folder can be empty until it is filled.\n\nControl panel:\n•	The control panel is a feature of the Windows operating system that allows the user to modify system settings and controls.\n\nLinux:\n•	Linux is the most used open-source operating system. Linux is software that sits underneath all of the other software on a computer, receiving requests from those programs and relaying these requests to the computer’s hardware.\n\nUNIX:\n•	UNIX is an operating system that manages the way the computer works by driving the processor, memory, disk drivers, keyboards, video monitors, etc.\n\nMobile Operating System:\n•	Mobile OS is an operating system that is specifically designed to run on mobile devices such as mobile phones, smartphones, etc."),
];
final chapter_4 = [
  Chapter(1, "What is word-processing?",
      "➡️ Word processing is an application software that provides extensive tools to create, view, edit, format, store and print text materials for human communication. Examples are Word Star, Microsoft Word, etc."),
  Chapter(2, "What is Microsoft Office Word 2010? Who developed it?",
      "➡️ Microsoft Office word 2010 is a full-featured word processing program that allows you to create professional looking documents.\n\nIt is developed by Microsoft Corporation, USA."),
  Chapter(3, "What are the advantages of Microsoft Office Word 2003?",
      "➡️ The advantages of Microsoft Office Word 2003 are:\n• Mature product with stable application,\n•	Gazillion features hidden in toolbars,\n•	Files created were binary representation of the content."),
  Chapter(
      4,
      "What is formatting a document? What is the default page margin in Word?",
      "➡️ Formatting is the process of enhancing the appearance of a document to make it more readable or attractive.\n\nDefault page margin in world is 1.25 inches at left and right and 1 inch at top and bottom."),
  Chapter(5, "What is page margin?",
      "➡️ Page margin is the space between the edge of page of word where the text lies."),
  Chapter(6, "What are headers and footers?",
      "➡️ A header is a text that appears at the top of every page in a document.\nA footer is a text that appears at the bottom of every page in a document."),
  Chapter(7, "What is Thesaurus?",
      "➡️ Thesaurus is the function of Microsoft word that makes it possible to look up synonyms and antonyms to words as user type with a few clicks of mouse."),
  Chapter(
      8,
      "Describe how the Mail Merge feature works. What are the advantages of using Mail Merge?",
      "➡️ Mail merge feature works in the following:\n•	Select document type,\n•	Select the starting document,\n• Select recipient,\n•	Write your letter,\n•	Preview the letters,\n•	Complete the merge.\n\nAdvantages of using mail merge are:\n•	It is simple and easy to use,\n• Conditional formatting or options,\n•	Makes your work neater and professional."),
  Chapter(9, "Write the steps to perform the following operations.",
      "To use the format painter:\n• Select the text or graphic that has the formatting that you want to copy,\n•	On the Home tab, in the Clipboard group, click Format Painter.\n\nTo add headers and footers:\n•	Select the Insert tab,\n•	Click either the Header or Footer command. A drop-down menu will appear,\n•	From the drop-down menu, select Blank to insert a blank or footer, or choose one of the built-in options,\n•	The design tab will appear on the Ribbon, and the header or footer will appear in the document,\n•	Type the desired information into the header or footer,\n•	When you’re finished, click Close Header and Footer in the Design tab, or hit the Esc key."),
  Chapter(
      10,
      "What is a spreadsheet? Give two examples of spreadsheet software.",
      "➡️ Spreadsheet is a program that accepts data in a tabular form and allows user to manipulate, calculate and analyze data in the desired manner.\n\nTwo examples of spreadsheet software are LOTUS 1-2-3 and Microsoft Excel."),
  Chapter(11, "Define the following.",
      "Workbook:\n•	Workbook is an Excel file that contains one or more worksheets.\n\nWorksheet:\n•	Worksheet is a single spreadsheet that contained cells organized by rows and columns."),
  Chapter(12, "What are the different types of data that MS-Excel recognizes?",
      "➡️ The different types of data that MS-Excel recognizes are:\n•	A numerical value,\n•	Text,\n•	Formula."),
  Chapter(13, "What are functions? Give the uses and syntax of SUM function.",
      "➡️ Functions is a predefined formula that performs calculations using specific values in a particular order.\n\nThe SUM function is used to adds all the numbers in a range of cells and syntax is =SUM."),
  Chapter(14, "What is meant by ‘range of cells’? How is it defined?",
      "➡️ A range of cells in an Excel file is a collection of selected cells.\n\nIt is defined by the address of two opposite or diagonally paired corner cells separated by a colon (:)."),
  Chapter(15, "What is a chart? Name some chart types available in MS-Excel.",
      "➡️ Chart is the pictorial representations of data.\n\nSome chart types available in MS-Excel are Colum chart, Line chart, Pie chart, Bar Graph, Area Chart, Scatter Graphs, Surface Charts, etc."),
  Chapter(16, "Differentiate between bar chart and column chart.",
      "Bar chart:\n1️⃣	A Bar chart illustrates comparisons among individual items.\n\nColumn chart:\n1️⃣	A Column chart show the changes in data over a period of time."),
  Chapter(17, "What do you mean by a data series?",
      "➡️ A data series is a row or column of numbers that are entered in a worksheet and plotted in your chart, such as a list of quarterly business profits."),
  Chapter(18, "Write the steps to perform the following tasks.",
      "To select a cell or range using the mouse:\n•	To select a single cell, click it,\n•	Click the upper-left cell in the group and drag down to the lower-right cell to select additional cells,\n•	To select nonadjacent cells, press and hold the Ctrl key as you click individual cells,\n•	To select an entire row or column of cells, click the row or column header,\n•	To select adjacent rows or column, drag over their headers,\n•	To select nonadjacent rows or columns, press Ctrl and click the header for those you want to select.\n\nTo enter a formula:\n•	Select the cell in which you want the formula’s calculation to appear,\n•	Type the equal to sign,\n•	Type the formula. The formula appears in the Formula bar,\n•	Press Enter to complete the formula.\n\nTo use AutoSum to select Common Functions:\n•	Select the cell where the answer will appear,\n•	Click on the Home tab,\n•	Click on the Autosum dropdown arrow and select the function you desire,\n• A formula will appear in the selected cell E24,\n•	Press Enter and the result will appear."),
  Chapter(19, "What is presentation software?",
      "➡️ Presentation software is a computer software package used to display information, normally in the form of a slide show."),
  Chapter(20, "What is Microsoft Office PowerPoint 2010?",
      "➡️ Microsoft Office PowerPoint 2010 is a complete presentation graphics program developed by Microsoft Corporation, USA."),
  Chapter(21, "State any three advantages of Microsoft Office PowerPoint 2010?",
      "➡️ Three advantages of Microsoft Office PowerPoint 2010 are:\n•	It can create paper printouts of the individual slides,\n•	It allows to animate objects and add narrations,\n•	It helps you to quickly create presentations."),
  Chapter(
      22,
      "What do you understand by PowerPoint view? What are the main views of Microsoft Office PowerPoint 2010?",
      "➡️ A PowerPoint view is a way of displaying your presentation onscreen.\n\nThe main views of Microsoft Office PowerPoint are:\n•	Normal,\n•	Slide Sorter,\n•	Master views,\n•	Slide Show view,\n•	Presenter view,\n•	Reading view."),
  Chapter(
      23,
      "What is normal view? Name the three working areas of normal view.",
      "➡️ Normal view is set to be the default presentation view and we use this view most of the time when making any changes to the current slide.\n\nThree working areas of normal view are:\n•	Outline tab,\n•	Slides tab,\n•	Slide pane."),
  Chapter(
      24,
      "What is the difference between slide view and slide shorter view?",
      "Slide sorter view:\n•	Slide sorter view gives view of slides in thumbnail form.\n•	It allows user to navigate easily between different slides.\n\nSlide view:\n•	Slide view deliver presentation to audience.\n•	It allows user to see graphics, timings, movies, animated effects, etc."),
  Chapter(25, "What is a placeholder?",
      "➡️ A placeholder is a container that is used to display content, such as text, table, picture, movies, sound, clip art, chart, SmartArt, etc."),
  Chapter(26, "What is meant by animation?",
      "➡️ Animation is a special visual effect that you can add to parts of the slides that enables the presenter to focus on important points as they are being presented."),
  Chapter(27, "What is meant by transition?",
      "➡️ Transition is the special effects used to introduce a slide during the slide show."),
  Chapter(
      28,
      "Write the steps to perform the following tasks in PowerPoint 2010.",
      "To add a new slide to a presentation:\n•	From the Home tab, click the bottom half of the New Slide command to open the menu of slide layout options,\n•	Select the slide you want to insert,\n•	A new slide will be added to your presentation.\n\nTo apply a WordArt Style to Text:\n•	Select a text box, or select some texts inside of the text box,\n•	Click the Format tab,\n•	In the WordArt Styles group, click the More drop-down arrow to view all of the available styles,\n•	Select the desired style preset to apply the style to your text.\n\nTo add animation to a presentation:\n•	Select an object,\n• Click the Animation tab,\n•	In the Animation group, click the More drop-down arrow to view the available animations,\n•	Select the desired animation effects,\n•	The object will now have a small number next to it show that it has an animation."),
];
final chapter_5 = [
  Chapter(1, "What is program?",
      "➡️ A program is a set of instructions that tells the computer how to solve a problem or perform a task."),
  Chapter(
      2,
      "What is a programming language? Name the categories of programming language.",
      "➡️ A programming language is a special language used to code a program.\n\nThe categories of programming language are:\n• Low-level language,\n• High-level language."),
  Chapter(3, "What is low level Language? Write down its’ type.",
      "➡️ The low-level language is a programming language that provides no abstraction from the hardware and it is represented in 0 or 1 forms.\n\nTypes of low-level language are:\n• Machine language or First-generation language,\n• Assembly language or Second-generation language."),
  Chapter(4, "What is an assembly language?",
      "➡️ Assembly language is the language written in simple English language, so it is easily understandable by the users."),
  Chapter(5, "What is High Level Language? Write any three examples of it.",
      "➡️ High level language are languages which use instruction that are closer to English and mathematical form.\n\nThree examples of high-level language are:\n• FORTRAN,\n• PROLOG,\n• MERCURY."),
  Chapter(6, "What is Fourth generation language?",
      "➡️ Fourth generation language is high-level computer language that allows nonprogrammer user to write programs to query databases and to generate custom reports."),
  Chapter(7, "Write any two differences between 4GL and 5GL.",
      "4GL:\n1️⃣ Programmer of 4GL have to specify the algorithm in order to solve a problem.\n2️⃣ Program designed with 4GL doesn’t have artificial intelligence.\n\n5GL:\n1️⃣ Programmers of 5GL only have to define the problem and constraints that need to be satisfied.\n2️⃣ Program designed with 5GL have artificial intelligence."),
  Chapter(
      8,
      "What is language translator? Explain the different types of language translator.",
      "➡️ Language translator is system software that converts a computer program from one language to another.\n\nDifferent types of language translator are:\nAssembler:\n• Assembler is used to translate the assembly language into machine language.\n\nCompiler:\n• Compiler is used to convert programs in high-level language to low-level language.\n\nInterpreter:\n• Interpreter is used to convert programs in high-level language to low-level language."),
  Chapter(9, "What is error? Explain the different types of error in details.",
      "➡️ Errors are the problems or the faults that occurs in the program, which makes the behavior of the program abnormal.\n\nDifferent types of error are:\nSyntax error:\n• Syntax error occurred at the compilation time.\n\nRun time error:\n• Run time error occurred during the execution-time.\n\nLogical error:\n• Logical error leads to an undesired output."),
  Chapter(10, "Explain different program design tools.",
      "➡️ Different program design tools are:\nAlgorithm:\n• Algorithm is the well-defined steps for performing a task or solving a problem.\n\nFlowchart:\n• Flowchart is the graphical representation of logical sequence of steps involved in programming.\n\nPseudocode:\n• Pseudocode is an informal language used to express the flow of a program."),
  Chapter(11, "Write the differences between algorithm and flowchart.",
      "Algorithm:\n1️⃣ Algorithm is the well-defined steps for performing a task or solving a problem.\n2️⃣ Algorithm is written in different steps.\n3️⃣ Algorithm is difficult to understand than the flowchart.\n\nFlowchart:\n1️⃣ Flowchart is graphical representation of logical sequence of steps involved in programming.\n2️⃣ Flowchart is shown in figure.\n3️⃣ Flowchart is easier to understand than algorithm."),
  Chapter(12, "What is flowchart? Write its advantages.",
      "➡️ Flowchart is graphical representation of logical sequence of steps involved in programming.\n\nAdvantages of flowchart are:\n• Flowchart is better way of communicating the logic,\n• Flowchart acts as guide or blueprint during system analysis,\n• Flowchart help in debugging process."),
  Chapter(
      13,
      "Write the difference between system flowchart and program flowchart.",
      "System flowchart:\n1️⃣ System flowchart deals with functionality of entire system.\n2️⃣ It is hard to understand.\n3️⃣ We can understand the entire system.\n\nProgram flowchart:\n1️⃣ Program flowchart deals with how the particular program works.\n2️⃣ It is easy to understand.\n3️⃣ We can understand how the program works."),
  Chapter(14, "Write short notes:",
      "Sequence:\n• Sequence structure consists of operations that are being executed sequentially.\n\nBCD:\n•	BCD stands for Binary Coded Decimal.\n• In BCD each digit of decimal number is represented by fix number of bits.\n\nASCII\n• ASCII stands for American Standard Code for Information Interchange.\n•	ASCII define a set of characters for encoding text documents on computer."),
  Chapter(
      15,
      "What is C programming? List any three features of C programming.",
      "➡️ C programming is a middle level structured programming language which is very close to the both low level language and high-level language.\n\nThree features of C programming are:\n• It is a structured programming language,\n•	It has rich and powerful set of operators,\n• It allows manipulation of internal process registers."),
  Chapter(16, "What are the important elements of C programming?",
      "➡️ The important elements of C programming are:\n• Pre-processor directive,\n• Functions,\n• Variables,\n• Statements,\n• Comments, etc."),
  Chapter(17, "What are C keywords? Give examples.",
      "➡️ C keywords are the words which have special meaning for the compiler.\n\nExamples are auto, const, break, case, char, int, etc."),
  Chapter(18, "What is a variable? How does it differ from constant?",
      "➡️ Variable is a named location in the memory that is used to store a value during a program execution.\n\nVariable is change in a program but constant is not change during the execution of a program."),
  Chapter(19, "What are the different types of constants in C programming?",
      "➡️ The different types of constants in C programming are:\n• Integer constant,\n•	Real constant,\n• Character constant,\n• String constant."),
  Chapter(
      20,
      "What are data type modifiers? Name the data type modifier with their memory consumptions.",
      "➡️ Data type modifiers are modifier used to change the meaning of the basic data type.\n\nData type modifier with their memory consumptions are:\n• Short int (2 byte),\n• Long int (4 byte),\n• Unsigned short (2 byte),\n•	Unsigned long int (4 byte)."),
  Chapter(
      21,
      "What are arithmetic operators? Name the arithmetic operators used in C programming.",
      "➡️ Arithmetic operators are the operators used for manipulating arithmetic data and perform arithmetic operations.\n\nArithmetic operators used in C programming are addition, subtraction, multiplication, division and modulus."),
  Chapter(
      22,
      "What is unary operator? What are the two types of unary operators use in C programming?",
      "➡️ The unary operators operate on one operand-variable or constant.\nTwo types of unary operators use in C programming are increment (++) and decrement (--)."),
  Chapter(23, "What is logical operator? State the rules of logical operators?",
      "➡️ Logical operator connects two or more relational expressions into one, or reverse the logic of an expression.\n\nLogical operators return TRUE if the expression evaluates to nonzero or FALSE if the expression evaluates to zero"),
  Chapter(
      24,
      "What is the difference between selection statement and looping statement?",
      "Selection statement:\n1️⃣ Selection statement select among a set of statements depending on the value of a controlling expression.\n2️⃣ If and switch statement are selection statement.\n\nLooping statement:\n1️⃣	Looping statement allows a set of instructions to be repeated a certain number of times.\n2️⃣	For loop, while loop and do while loops are looping statement."),
  Chapter(25, "What is looping?",
      "➡️ Looping is the repetition of set of instruction for certain number of times while the condition set for it remains true."),
  Chapter(26, "Write the differences between Break and continue statement",
      "Break statement:\n1️⃣ Break statement is used to terminate the loops.\n2️⃣	Break statement is used in loop and switch case.\n\nContinue statement:\n1️⃣ Continue statement is used to continue the next iterations of loop.\n2️⃣ It is used in loop only."),
  Chapter(27, "Write the differenences between While and do-while",
      "While loop:\n1️⃣	The while loop evaluates the condition first and then execute the statements.\n2️⃣ There is no semicolon at the end of while.\n\ndo-while loop:\n1️⃣ The do-while loop executes the statements first before evaluating the condition.\n2️⃣ There is compulsion of semicolon at the end of do-while loop."),
  Chapter(28, "What is Array?",
      "➡️ An Array is the collection of data of the same datatypes. Array is used to store data of the same types under the same name."),
  Chapter(29, "What is String?",
      "➡️ String is the group of characters. In c programming we have different types of built-in functions for string. Some of them are:\n •Strlen(): To find the length of string.\n •strcat(): To concatenate two string. \n•strcpy(): It is used to copy a string from one source to another source.\n•strlwr():This string function converts all characters of string to lowercase\n•strupr():This function converts all characters of a string to uppercase.")
];
final chapter_6 = [
  Chapter(1, "What is Web development?",
      "➡️ Web development means developing websites for hosting via the internet or intranet. Web development range from creating a static page to a complex web-based application like e-commerce."),
  Chapter(2, "What is website?",
      "➡️ website is the collection of webpages. webpages are developed using html which consists different kind of contents, images, audios etc."),
  Chapter(3, "What is web hosting and web publishing?",
      "➡️ Web hosting makes it possible to access websites through the internet. When a user enters the domain name, it consists the address of the company's computer which contains all your files. Then the computer sends back all files to the user's browser to display content.\nWeb publishing refers to uploading content to the internet via web servers."),
  Chapter(4, "What is domain name?",
      "A domain name is the name of your website users use to visit your website. Domain name is later converted to Ip address to locate your website. Since it was difficult to remember the IP address of the website domain name was introduced for efficiency."),
  Chapter(5, "What is an HTML? List out any three advantages of HTML?",
      "➡️ HTML (HyperText Markup Language) is the basic building-blocks of webpages.\n\nThree advantages of HTML are:\n• It is easy to code,\n• HTML-based web sites are static,\n• HTML-based web sites are easy to design and have low development cost."),
  Chapter(6, "What are HTML tags and where are they used?",
      "➡️ HTML tags are the instruction which define that how web browser will format and display the content.\n\nThey are used to create html document."),
  Chapter(7, "What is HTML element? What are the two types of HTML elements?",
      "➡️ HTML element is a fundamental component of the structure of an HTML.\n\nTwo types of HTML elements are Container element and Empty element."),
  Chapter(
      8,
      "What are the document structure element? Explain each of them in short.",
      "➡️ Document structure element are the element of HTML which are used for confirmation of HTML element.\n\nThey are:\nHTML element:\n• The tag <HTML>tells the document is an HTML document.\n\nHEAD element:\n• The HEAD element marks the position of the head section.\n\nBODY element:\n• Body element include the entire content of the document that is supposed to the display in the web browser window."),
  Chapter(9, "What is ordered list?",
      "➡️ The order list has a number or letter before an item. The order list begins with <OL> tag and must end with </OL> tag."),
  Chapter(10, "What is the difference between CELLSPACING and CELLPADDING?",
      "➡️ CELLSPACING gives the space between cells and CELLPADDING gives the space between the border of table cell and its component."),
  Chapter(
      11,
      "What do you understand by the term “hyperlink”? Which element is used for hyperlinking?",
      "➡️ Hyperlink is to link other web page, the section of same web pages or website.\nThe element used for hyperlinking is <A>…. </A> tag."),
  Chapter(12, "What is CSS? Write the advantages of CSS.",
      "➡️ CSS (Cascading Style Sheets) is a style sheet language which is used to describe the look and formatting of a document written in markup language.\n\nThe advantages of CSS are:\n• Device Compatibility,\n• Faster website speed,\n• Ability to re-position."),
  Chapter(13, "Write down the syntax of CSS.",
      "➡️ The syntax of CSS is: Selector {property: value).\nBody {color: yellow; font-size: 13px;}.\n"),
  Chapter(14, "What are the different types of CSS? Explain.",
      "➡️ The different types of CSS are:\nExternal CSS:\n• External CSS is used to make changes on multiple pages.\n\nInternal CSS:\n•	Internal CSS is used to add a unique style for single document.\n\nInline CSS:\n•	Inline CSS is used to insert stylesheet in html document. "),
  Chapter(15, "Write the different properties of CSS.",
      "➡️ The different properties of CSS are:\n• Color,\n• Font-size,\n•	Background-color,\n• Font- family, etc."),
  Chapter(16, "What is CSS selector?",
      "➡️ CSS selector is the HTML element where the CSS is applied.CSS selectors select HTML elements according to its id, class, type, attribute, etc."),
  Chapter(
      17,
      "Name the property for controlling the image position in the background.",
      "➡️ The property for controlling the image position in the background is background-position.\nExample: background-position: center;"),
  Chapter(
      18,
      "Where the inline, embedded and external style sheets are written?",
      "➡️ External style sheet is written in outside from the html document and save with .CSS extension.\nEmbedded stylesheet is written in html document at head section.\nInline stylesheet is written with html code at body section."),
];
final chapter_7 = [
  Chapter(1, "What is multimedia?",
      "➡️ Multimedia is a computer-delivered electronic system that deals with different types of media like video, text, graphics, etc."),
  Chapter(2, "What are the different types of media in a multimedia?",
      "➡️ The different types of media in a multimedia are text, audio, images, video, animation, etc."),
  Chapter(3, "Explain the components of multimedia.",
      "➡️ The components of multimedia are:\nText:\n• In multimedia text is used as headlines, subtitles and slogan.\n\nAudio:\n• Audio deals with synthesizing, recording and playback of audio or sound.\n\nGraphics:\n•	Graphics deal with the generation, representation, manipulation and display the pictures.\n\nAnimation:\n• Animation is the process of displaying images in a rapid sequence to create the illusion of movement.\n\nVideo:\n•	Video deals with the recording and display of a sequence of images at a reasonable speed."),
  Chapter(4, "Write advantages and disadvantages of multimedia.",
      "Advantages:\n•	It helps to share, views ideas and information in more effective and attractive way,\n•	It helps to make advertisement more attractive,\n• It makes presentation more interesting,\n• It makes teaching learning easier, attractive and effective.\n\nDisadvantages:\n•	It is expensive,\n•	It needs well trained manpower,\n•	Large files are time consuming to transfer,\n•	The device used for multimedia can be damaged."),
  Chapter(
      5,
      "What do you mean by animation? Why is it important in multimedia application?",
      "➡️ Animation is the process of displaying still images in a rapid sequence to create the illusion of movement.\n\nAnimation is important in multimedia application because animation makes it easier to portray the different aspects of multimedia application."),
  Chapter(
      6,
      "What is a multimedia computer system? What are the hardware components of multimedia system? ",
      "➡️ A multimedia computer system is a computer equipped with special hardware and software that makes multimedia possible.\n\nThe hardware components of multimedia system are:\n•	Central Processing Unit (CPU),\n•	Hard disk,\n•	Random Access Memory (RAM),\n• High resolution monitors,\n•	Sound card and speakers,\n•	Keyboards and pointing devices."),
  Chapter(7, "What is the role of multimedia in education?",
      "➡️ Multimedia based education greatly enhance traditional education by providing the student with options of individual attention. It brings presentations alive with sound, video, animations to become active participation."),
  Chapter(8, "How is multimedia useful in business?",
      "➡️ In business the multimedia provided a medium to promote, sell, teach and communication in new interactive ways. In business multimedia also used for virtual showrooms. It is also used for providing employee training, advertising and selling products."),
  Chapter(9, "What is virtual reality?",
      "➡️ Virtual reality is the use of computer technology to create simulated environment."),
  Chapter(10, "Write any five application of multimedia.",
      "➡️ The five applications of multimedia are:\n• Education,\n• Entertainment,\n• Business,\n• Software training,\n• Mass media."),
];
final chapter_8 = [
  Chapter(1, "What is Information and Communication Technology (ICT)?",
      "➡️ ICT is applied area of computer science, electronics, telecommunication and various field that deals with processing, storing and transmitting of information."),
  Chapter(2, "What is computer ethics?",
      "➡️ Ethics is the principle that shows the behavior of an individual. So, computer ethics continues to create an ethical standard that addresses new issues created by new technology.\nImportance of computer ethics are:\n• To control palgarism\n• To control unwanted spam\n• To discourage dishonest business strategy"),
  Chapter(3, "What is security threat and its types?",
      "➡️ Security threat is a possible danger that may or may not happen in the future. It can affect an individual’s computer and business computers at risk.\n Some types of security threat are:\n• Interception: IT refers to stealing the information or unauthorized access to data.\n• Interruption: It means making service unavailable to other user.\n• Modification: It involves changing data or tampering with the services.\n• Fabrication: It refers to the activity of adding data to alter the meaning of data."),
  Chapter(4, "What is cryptography? Explain briefly.",
      "➡️ Cryptography is the process of providing security to the information shared between two individuals. Encryption and decryption are the two processes of providing security to information. Encryption is carried out by converting plain text to cipher text using various techniques. It is converted to ciphertext using keys so that attacker wouldn’t be able to understand the message. When the receiver receives the message, the ciphertext is decrypted back to plain text, which is called decryption."),
  Chapter(5, "What is Data security?",
      "➡️ A major threat to data security is packet sniffing. It is used to steal users Ids, passwords, and credit card details. Since many bank transactions are done online, data security has become the main concern for every business organization."),
  Chapter(6, "What is Cyber law?",
      "➡️ Cyber law is the area of law that deals with the Internet’s relationship to technological and electronic elements, including computers, software, hardware and information system (IS)."),
  Chapter(7, "What is digital signature? Why it is necessary?",
      "➡️ Digital signature is simply a small block of data that is attached to documents you sign.\n\nIt is necessary because:\n• It added security,\n• It maintains high standard,\n• It has global acceptance and legal compliance."),
  Chapter(8, "What is Intellectual Property (IP)? Write down its categories.",
      "➡️ Intellectual Property refers to the protection of creations of the mind, which have both a moral and a commercial value.\n\nCategories:\n• Industrial property, which includes inventions, trademarks, industrial design, etc,\n• Copyright, which includes literary and artistic works."),
  Chapter(9, "Explain Cyber law of Nepal in details.",
      "• Cyber law of Nepal is also known as Electronic Transaction and Digital Signature Act-Ordinance was introduced in Nepal in 2061 BS.\n• It was formulated mainly to legalize the different trading activities through the global computer network.\n• It contains a strong provision of punishment against cyber-crime.\n• A controller of public key certifying authorities has been appointed by the government."),
  Chapter(10, "What is Cybercrime? List some of the example of Cybercrime.",
      "➡️  Cybercrime is criminal activity done using computers and the internets.\nSome examples of Cybercrime are:\n• Hacking,\n• Phising,\n• Cyberstalking,\n• Computer viruses,\n• Cybertheft."),
  Chapter(11, "What is Malicious software?",
      "➡️ The application that brings harm to a computer system is called malicious software. It is used to disrupt the operation, delete information, steal credentials, or access the system. Worms, viruses, and trojan horses are some examples of malicious software(malware)."),
  Chapter(
      12,
      "Write some Objectives of National Information and Communication Technology Policy.",
      "➡️ Some Objectives of National Information and Communication Technology Policy are:\n• To empower and facilitate Nepal’s participation in the Global Knowledge Society,\n• To promote ICT to further productivity among the sectors that is key drivers of the national economy,\n• To transfer Government service delivery regime by promoting transparency, efficiency, inclusiveness and participation,\n• To promote cost-effective and qualitative last-mile access technologies,\n• To create easily accessible affordable and innovative public access point, etc."),
  Chapter(13, "Write short notes on:",
      "Hacking:\n• Hacking is the activity of breaking into a computer system to gain an unauthorized access.\n\nCyberstalking:\n• Cyberstalking is the activity of torturing the individuals by using internet.\n\nTelecommunication Law:\n• Telecommunication is a communication between parties from one to another. Telecommunication system also fall within the territory of cyber space and therefore would form an integral part cyber law.\n\nDigital Signature Law:\n• Digital signature law provides a legal framework to facilitate and safeguard electronic transaction in the electronic medium. Various laws have been passed internationally to facilitate the use of electronic records and digital signatures.\n\nPhishing:\n• The act of attempting to acquire sensitive information like usernames, passwords and credit card details by disguising as a trustworthy source."),
];
